ENABLE_TREND_AGENT = True
ENABLE_RECOMMENDATIONS = True
ENABLE_APPROVE_WORKFLOW = True
ENABLE_BULK_UPLOAD = True

# V2 Feature Flags
ENABLE_AGENTREACH_IMPORT = True
ENABLE_AUTO_MODE = True  # Phase 5
ENABLE_OUTRO_ROTATION_V2 = True
ENABLE_DASHBOARD = True
ENABLE_SYSTEM_HEALTH = True

# Facebook -> second YouTube channel automation
ENABLE_FACEBOOK_SECOND_CHANNEL = True
